[target.x86_64-pc-windows-gnu]
#linker = "rust-lld"
#rustflags = ["-C", "link-arg=-eDllMainCRTStartup"]
#linker = "H:\\w64devkit\\bin\\gcc.exe"
linker = "C:\\Users\\Pinnsvin\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\bin\\self-contained\\x86_64-w64-mingw32-gcc.exe"